use_frameworks!

target 'MyFirstGitHubProject_Example' do
  pod 'MyFirstGitHubProject', :path => '../'

  target 'MyFirstGitHubProject_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
