use_frameworks!

target 'GithubUploadLib_Example' do
  pod 'GithubUploadLib', :path => '../'

  target 'GithubUploadLib_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
